repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.4
  hooks:
    - id: trailing-whitespace
- repo: git://github.com/pre-commit/mirrors-jshint
  sha: v2.9.5
  hooks:
    - id: jshint
- repo: git://github.com/pre-commit/mirrors-fixmyjs
  sha: v2.0.0
  hooks:
    - id: fixmyjs
      args: ['-l', '-c', '.jshintrc']
      exclude: '(src\/js\/lz-string.js)'
